### ISSUE TITLE
PHP 7 Support timeline

### ISSUE THREAD

**Issue by courtneybbentley** [itamart/moodle-mod_dataform#15]
I'm thrilled to hear in the other open issue you are working on a new version release. Currently, it appears that the interface for adding and editing dataforms is broken when installing on Moodle (in 3.0.1-3.3+) using PHP 7, but seems to work with PHP 5.6 on those releases. With the release of Moodle 3.4, Moodle has dropped support for PHP 5.6. Is PHP 7 support expected with your next release?

**Comment by julianrubisch** [comment]
an update on this ticket would be very appreciated!

**Comment by itamart** [comment]
3.3.2 which supports PHP 7 has just been released.
