### ISSUE TITLE
Can't set image size on 2.8.6 version

### ISSUE THREAD

**Issue by mastnym** [itamart/moodle-mod_dataform#6]
If you try to add picture field in v2.8.6 there's no way how to specify dimensions of the image. Everything works fine on master.

**Comment by itamart** [comment]
See https://tracker.moodle.org/browse/CONTRIB-5834. Resolved not yet released. You can try applying commit https://github.com/itamart/moodle-mod_dataform/commit/c1f0e4357d8c620b010a7f4e7486c9a6d7dc08bd. A possible workaround is to enclose the image in a container element and specify dimensions in the activity css. hth :-)

**Comment by mastnym** [comment]
Thanks Itamar, I patched this, looking for release. Martin
