### ISSUE TITLE
Warning: Declaration of...

### ISSUE THREAD

**Issue by nitro2010** [itamart/moodle-mod_dataform#7]
Warning: Declaration of mod_dataform\plugininfo\dataformfield::load_settings(mod_dataform\plugininfo\part_of_admin_tree $adminroot, $parentnodename, $hassiteconfig) should be compatible with core\plugininfo\base::load_settings(part_of_admin_tree $adminroot, $parentnodename, $hassiteconfig) in /opt/lampp/htdocs/moodle/mod/dataform/classes/plugininfo/dataformfield.php on line 212

Warning: Declaration of mod_dataform\plugininfo\dataformview::load_settings(mod_dataform\plugininfo\part_of_admin_tree $adminroot, $parentnodename, $hassiteconfig) should be compatible with core\plugininfo\base::load_settings(part_of_admin_tree $adminroot, $parentnodename, $hassiteconfig) in /opt/lampp/htdocs/moodle/mod/dataform/classes/plugininfo/dataformview.php on line 212

**Comment by itamart** [comment]
https://github.com/itamart/moodle-mod_dataform/commit/099f3839aec15d9f48743762f488b076b9903311
