### ISSUE TITLE
Dataform view - folder missing in upgrade to version 3.0

### ISSUE THREAD

**Issue by hartmut1s** [itamart/moodle-mod_dataform#9]
Hi Itamar,

Thank you for the updated versions. I upgraded Dataform, Dataform access-view and Dataform notification to the version for Moodle 3.0. During the upgrade of Dataform, I got a "missing file" for Dataform view and had to manually add the folder. Now the Plugins overview looks like this:
![dataform view missing in upgrade to 3 0 version](https://cloud.githubusercontent.com/assets/8261898/15214492/b9fd3776-1890-11e6-9054-300c1ed6c242.jpg)

With kind regards,
Hartmut

**Comment by itamart** [comment]
Hi Hartmut. Not sure what the issue is. The dataformview field is not yet included in the standard release of the Dataform and is not upgraded with the Dataform standard upgrade.

**Comment by hartmut1s** [comment]
Hi Itamar,

I did the upgrade in Moodle, i.e., Site administration > Plugins > Plugins overview. Somehow the folder Dataformview in mod\dataform\field\ got deleted during the upgrade process, which resulted in a "missing file on disk." This happened in my test site as well as in the production site.

I understand that Dataform view field is not yet included in the standard release. Should I delete this folder or can I still keep it although it is not yet updated?

With kind regards,
Hartmut

**Comment by itamart** [comment]
The upgrade issue might be b/c of the plugin dependency version, but that would likely be a Moodle issue in the upgrade process.

Older Dataform addons can still work with newer Dataform versions. They depend on older Dataform versions which means that they will be recognized by any Dataform version from that dependency onward. Of course, if there are local API changes in the newer Dataform versions, it might break functionality of the older addon.

The current version of the dataformview field should work. If you encounter any problem you can open a tracker issue and we can take it from there.

**Comment by hartmut1s** [comment]
Thank you for the explanation, Itamar. I will keep the Dataform view field and use the Moodle tracker in case I encounter a problem. 
With kind regards,
Hartmut
